#!/usr/bin/env node
// Turn the namespace catalogues into one prebuilt bundle per kind of website,
// so a website physically receives only the sections that concern it.
//
// The bundle is emitted twice: as JSON, which the checks read, and inlined in
// a JavaScript module, which the websites import. Inlining rather than
// importing the JSON keeps the module loadable by plain Node as well as by a
// bundler, which is what makes the same file usable in a test and in a build.

import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const registry = JSON.parse(readFileSync(join(root, 'namespaces.json'), 'utf8'))
const dist = join(root, 'dist')

const catalogues = {}
for (const namespace of registry.namespaces) {
  catalogues[namespace] = {}
  for (const file of readdirSync(join(root, namespace)).filter((f) => f.endsWith('.json'))) {
    const language = file.slice(0, -'.json'.length)
    catalogues[namespace][language] = JSON.parse(
      readFileSync(join(root, namespace, file), 'utf8')
    )
  }
}

rmSync(dist, { recursive: true, force: true })

for (const [bundle, namespaces] of Object.entries(registry.bundles)) {
  const languages = new Set(namespaces.flatMap((n) => Object.keys(catalogues[n])))
  const merged = {}
  for (const language of [...languages].sort()) {
    // Keys carry their namespace, so the sections cannot collide; the order is
    // the registry's, and exists only to make the output stable.
    const entries = {}
    for (const namespace of namespaces) Object.assign(entries, catalogues[namespace][language])
    merged[language] = Object.fromEntries(
      Object.keys(entries).sort().map((key) => [key, entries[key]])
    )
  }

  mkdirSync(join(dist, bundle), { recursive: true })
  for (const [language, entries] of Object.entries(merged)) {
    writeFileSync(
      join(dist, bundle, `${language}.json`),
      JSON.stringify(entries, null, 2) + '\n',
      'utf8'
    )
  }
  writeFileSync(
    join(dist, bundle, 'index.js'),
    '// Generated by tools/build.mjs — do not edit.\n' +
      `export const catalogues = ${JSON.stringify(merged, null, 2)}\n\n` +
      'export default catalogues\n',
    'utf8'
  )
  const counts = Object.entries(merged)
    .map(([language, entries]) => `${language} ${Object.keys(entries).length}`)
    .join(', ')
  console.log(`  ${bundle}: ${namespaces.join(' + ')} — ${counts}`)
}
